# // the best until now, DO NOT LOOSE IT
services:
  couchdb:
    image: couchdb:3.3.1
    container_name: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=user
    volumes:
      - ~/docker/couchdb_data:/opt/couchdb/data
    networks:
      - app-network

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - API_NAME=api
      - API_SDK_PASSWORD=user
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=user
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_STATE_DB=state_ims
      - COUCHDB_LEDGER_DB=ledger_ims
      - PORT=3000
    depends_on:
      - couchdb
    networks:
      - app-network

volumes:
  couchdb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/docker/couchdb_data

networks:
  app-network:
    external: true
    name: blockchainims_app-network
