# do not touch! it is working after 3 days :)
version: '3'
services:
  # Node.js application
  node:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"  # Host port 3000 mapped to container port 3000
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_STATE_DB: state_ims
      COUCHDB_LEDGER_DB: ledger_ims
      PORT: 3000
      HOST: 0.0.0.0
    depends_on:
      - couchdb  # This ensures CouchDB starts first

  # CouchDB container
  couchdb:
    image: couchdb:3.4.2
    container_name: couchdb
    ports:
      - "6984:5984"  # Expose CouchDB on port 6984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data  # Persist data between restarts

# Volumes to persist CouchDB data
volumes:
  couchdb_data:
