version: '3.8'

networks:
  fabric_v4:   # New network for the v4 version
    driver: bridge # Use the bridge network driver (default)
  blockchainims_v4_fabric_custom:  # Correct name of the existing network for v4
    external: true

services:
  # Node.js application for blockchainIMS_v4
  node_v4:
    build: .
    container_name: node-v4-app
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      COUCHDB_HOST: couchdb_v4  # CouchDB instance for v4
      COUCHDB_PORT: 5984
      COUCHDB_STATE_DB: state_ims_v4
      COUCHDB_LEDGER_DB: ledger_ims_v4
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      - fabric_v4   # Connect to the new fabric_v4 network
    depends_on:
      - couchdb_v4

  # Independent CouchDB instance for blockchainIMS_v4
  couchdb_v4:
    image: couchdb:3.4.2
    container_name: couchdb_v4
    ports:
      - "5983:5984"  # Map CouchDB to host port 5983
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_v4_data:/opt/couchdb/data  # Persist data
    networks:
      - fabric_v4   # Connect to the new fabric_v4 network

  # Fabric CA service for registering users for v4
  fabric-ca-v4:
    image: hyperledger/fabric-ca:latest
    container_name: fabric-ca-v4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "4444:7054"  # Map CA server port to 4444
    volumes:
      - fabric-ca-server-v4-volume:/etc/hyperledger/fabric-ca-server
      - ./certs:/fabric-network/certs  # Mount local certs folder
    networks:
      - fabric_v4   # Connect to the new fabric_v4 network
    command: sh -c 'fabric-ca-server start -b admin:adminpw'

  # Peer container for v4
  peer0.org1.example.com-v4:
    container_name: peer0.org1.example.com-v4
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.org1.example.com-v4
      - CORE_PEER_ADDRESS=peer0.org1.example.com-v4:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_FILESYSTEMPATH=/var/hyperledger/production
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb_v4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    ports:
      - "7051:7051"
    volumes:
      - peer0_v4_data:/var/hyperledger/production
    depends_on:
      - couchdb_v4
    networks:
      - fabric_v4   # Connect to the new fabric_v4 network

volumes:
  couchdb_v4_data:  # Volume for CouchDB instance
  fabric-ca-server-v4-volume:  # Volume for Fabric CA
  peer0_v4_data:  # Volume for peer0.org1.example.com-v4
